#!/bin/sh
#
# Copyright (C) 2013-2014 OpenMediaVault Plugin Developers
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

ELFINDER_SITE_CONF="/etc/nginx/openmediavault-webgui.d/openmediavault-elfinder-site.conf"

if [ -e "${ELFINDER_SITE_CONF}" ]; then
    rm ${ELFINDER_SITE_CONF}
fi

cat <<EOF > "${ELFINDER_SITE_CONF}"
location /elfinder/ {
    alias /usr/share/elfinder/;
    index index.html;
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm-openmediavault-elfinder.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }
    location = /elfinder/favicon.ico {
        log_not_found off;
        access_log off;
    }
    location = /elfinder/robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }
    location /elfinder/ {
        try_files \$uri \$uri/ /elfinder/php/index.php?\$args;
    }
    location ~ /elfinder/\. {
        deny all;
    }
    location ~* /elfinder/(?:config)/.*\.php$ {
        deny all;
    }
    location ~* /elfinder/\.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires max;
        log_not_found off;
    }
}
EOF

exit 0
