#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2020 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

FILENAME="master"
FULLNAME="${FILENAME}.zip"
LINK="https://github.com/icersong/elFinder/archive/${FULLNAME}"
FILE="/tmp/${FULLNAME}"
FOLDER="/tmp/elfinder-master"
INSTALL_DIR="/usr/share/elfinder"
WORKING_DIR="/media"
CONFIG_FILENAME=".htusers.php"
CONFIG_FILE="${INSTALL_DIR}/config/${CONFIG_FILENAME}"
SAVED_CONFIG="/tmp/${CONFIG_FILENAME}"
USERNAME="www-data"
GROUPNAME=users

case "$1" in
    configure)
        if ! getent passwd ${USERNAME} >/dev/null 2>&1; then
            echo "Adding ${USERNAME} user..."
            useradd --create-home --groups ${GROUPNAME} --no-user-group --shell /usr/sbin/nologin ${USERNAME}
        else
            echo "${USERNAME} user already exists."
        fi

        echo "Installing elFinder..."

        # backup config file
        if [ -f "${CONFIG_FILE}" ]; then
            cp "${CONFIG_FILE}" "${SAVED_CONFIG}"
        fi

        rm -rf ${INSTALL_DIR}
        mkdir -p ${INSTALL_DIR}
        wget ${LINK} -O ${FILE}
        unzip ${FILE}
        mv elFinder-master ${INSTALL_DIR}
        cp -f ${INSTALL_DIR}/php/connector.minimal.php-dist \
          ${INSTALL_DIR}/php/connector.minimal.php
        ln -s ${WORKING_DIR} ${INSTALL_DIR}/files
        mkdir ${WORKING_DIR}/.trash
        mkdir ${WORKING_DIR}/.trash/.tmb
        chown -R ${USERNAME}:${GROUPNAME} ${WORKING_DIR}/.trash
        if [ -f "${FILE}" ]; then
            rm -f ${FILE}
        fi

        # restore config file or new config file
        if [ -f "${SAVED_CONFIG}" ]; then
            mv "${SAVED_CONFIG}" "${CONFIG_FILE}"
        fi
#         new config file
#         else
#             cat <<EOF > ${CONFIG_FILE}
# EOF
#         fi

        # ./usr/share/openmediavault/mkconf/nginx.d/90-elfinder
        # ./usr/share/openmediavault/mkconf/php7.3-fpm.d/90-elfinder

        omv-mkconf php7.3-fpm
        service php7.3-fpm reload

        omv-mkconf nginx
        service nginx reload

        echo "Default username is:  admin"
        echo "Default password is:  openmediavault"

        # Activate package triggers.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale

        # omv_purge_internal_cache
        # omv_install_locale

        # Initialize and migrate configuration database.
        echo "Updating configuration database ..."
        omv-confdbadm create "conf.service.elfinder"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.service.elfinder" "${2}"
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
